eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
server:
  port: 9998
spring:
  application:
    name: Ribbon-Client