tpd:
  peer1Port: 8766
  peer2Port: 8763


management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'

---
spring:
  profiles: peer1
  application:
    name: spring-cloud-eureka-client-peer1
  eureka:
    instance:
      hostname: localhost
      appname: eureka-cluster
    client:
      serviceUrl:
        defaultZone: http://localhost:${tpd.peer2Port}/eureka
      register-with-eureka: true
      fetch-registry: true
server:
  port: ${tpd.peer1Port}

---
spring:
  profiles: peer2
  application:
    name: spring-cloud-eureka-client-peer2
  eureka:
    instance:
      hostname: localhost
      appname: eureka-cluster
      preferIpAddress: true
    client:
      serviceUrl:
        defaultZone: http://127.0.0.1:${tpd.peer1Port}/eureka
      register-with-eureka: true
      fetch-registry: true
server:
  port: ${tpd.peer2Port}
