tpd:
  peer1Port: 8766
  peer2Port: 8753
  peer3Port: 8754
  peer4Port: 8755
  peer5Port: 8756

#
#management:
#  endpoint:
#    health:
#      enabled: true
#      show-details: always
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      base-path: /
#      exposure:
#        include: '*'
#
#---
#spring:
#  profiles: Article
#  application:
#    name: Article
#  eureka:
#    instance:
#      hostname: localhost
#      appname: eureka-cluster
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:${tpd.peer2Port}/eureka
#      register-with-eureka: true
#      fetch-registry: true
#server:
#  port: ${tpd.peer1Port}
#application:
#  words: [a, the]
#---
#spring:
#  profiles: Adjective
#  application:
#    name: Adjective
#  eureka:
#    instance:
#      hostname: localhost
#      appname: eureka-cluster
#      preferIpAddress: true
#    client:
#      serviceUrl:
#        defaultZone: http://127.0.0.1:${tpd.peer1Port}/eureka
#      register-with-eureka: true
#      fetch-registry: true
#server:
#  port: ${tpd.peer2Port}
#application:
#  words: [resonable, leaky, suspicious, ordinary, unlikely]
#---
#spring:
#  profiles: Noun
#  application:
#    name: Noun
#  eureka:
#    instance:
#      hostname: localhost
#      appname: eureka-cluster
#      preferIpAddress: true
#    client:
#      serviceUrl:
#        defaultZone: http://127.0.0.1:${tpd.peer1Port}/eureka
#      register-with-eureka: true
#      fetch-registry: true
#server:
#  port: ${tpd.peer2Port}
#application:
#  words: [boat, book, vote, seat, backpack, partition, groundhog]
#---
spring:
  profiles: Verb
  application:
    name: Verb
  eureka:
    instance:
      hostname: localhost
      preferIpAddress: true
    client:
      serviceUrl:
        defaultZone: http://127.0.0.1:${tpd.peer1Port}/eureka
      register-with-eureka: true
      fetch-registry: true
server:
  port: ${tpd.peer2Port}
application:
  words: ran,knew,had,saw,bought
#---
#spring:
#  profiles: Subject
#  application:
#    name: Subject
#  eureka:
#    instance:
#      hostname: localhost
#      appname: eureka-cluster
#      preferIpAddress: true
#    client:
#      serviceUrl:
#        defaultZone: http://127.0.0.1:${tpd.peer1Port}/eureka
#      register-with-eureka: true
#      fetch-registry: true
#server:
#  port: ${tpd.peer2Port}
#application:
#  words: [I, You, He, She, It]