
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
# Application-wide configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
server:
  port: 8752
spring:
  config:
    activate:
      on-profile: Verb
  application:
    name: Verb
words: ran, knew, had, saw, bought
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
server:
  port: 8754
spring:
  config:
    activate:
      on-profile: Article
  application:
    name: Article
words: a, the
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
server:
  port: 8755
spring:
  config:
    activate:
      on-profile: Adjective
  application:
    name: Adjective
words: resonable, leaky, suspicious, ordinary, unlikely
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
server:
  port: 8756
spring:
  config:
    activate:
      on-profile: Noun
  application:
    name: Noun
words: boat, book, vote, seat, backpack, partition, groundhog
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
server:
  port: 8757
spring:
  config:
    activate:
      on-profile: Subject
  application:
    name: Subject
words: I, You, He, She, It
